# ML Zoomcamp Module 1 - HW

By Jayon Lihm (2025. 10. 02)

In [1]:
import numpy as np
import pandas as pd

## Q1. Pandas version

In [2]:
pd.__version__

'2.3.3'

In [3]:
data_file = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'
df = pd.read_csv(data_file)
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Q2. Records count - 9704

In [4]:
df.shape

(9704, 11)

## Q3. Fuel types - 2

In [6]:
df.fuel_type.nunique()

2

## Q4. Missing values - 4 columns

In [22]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [23]:
(df.isnull().sum() > 0).sum()

np.int64(4)

## Q5. Max fuel efficiency - 23.75

In [25]:
df['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [36]:
df[ df['origin'] == 'Asia' ]['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

## Q6. Median value of horsepower - No

In [37]:
df['horsepower'].median()

np.float64(149.0)

In [45]:
df['horsepower'].value_counts().idxmax()

np.float64(152.0)

In [46]:
most_freq_hp_value = df['horsepower'].value_counts().idxmax()

In [49]:
df['horsepower'].fillna(most_freq_hp_value)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [51]:
df['horsepower'].sum()

np.float64(1346317.0)

In [52]:
df['horsepower'].fillna(most_freq_hp_value).sum()

np.float64(1453933.0)

In [53]:
df['horsepower'].fillna(most_freq_hp_value).median()

np.float64(152.0)

## Q7. Sum of weights - 0.51

In [58]:
X = df[ df['origin'] == 'Asia' ][ ['vehicle_weight', 'model_year'] ].head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [63]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [62]:
y = np.array( [1100, 1300, 800, 900, 1000, 1100, 1200] )

In [66]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [67]:
sum(w)

np.float64(0.5187709081074025)