## Module 1-7: Intro to Numpy

In [3]:
import numpy as np

### Creating Arrays

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5) ## creates array with a given number
## size = 10

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
[1, 2, 3, 5, 7, 12] ## python list

[1, 2, 3, 5, 7, 12]

In [11]:
a = np.array([1, 2, 3, 5, 7, 12])

In [12]:
a[2]

np.int64(3)

In [13]:
a[2] = 10 ## change value
print(a)

[ 1  2 10  5  7 12]


In [14]:
np.arange(10) ## creates from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0, 1, 11) 
# from 0 to 1 with n elements=11

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [21]:
np.linspace(0, 100, 11) 

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-demensional arrays

In [23]:
np.zeros( (5, 2) ) ## 5 rows, 2 cols

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array( [ [1,2,3],
            [4, 5, 6],
            [7, 8, 9] ])
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
n[0, 1] = 20
print(n)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [29]:
n[0] ## row number 0

array([ 1, 20,  3])

In [30]:
n[1] ## row number 1

array([4, 5, 6])

In [31]:
n[2] = [1, 1, 1] ## replace row number 2
n 

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [33]:
n[:, 1] ## column number 1

array([20,  5,  1])

In [34]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [36]:
n[:, 2] = [0, 0, 0]
n

array([[ 1, 20,  0],
       [ 4,  5,  0],
       [ 1,  1,  0]])

### Randomly generated arrays

In [43]:
np.random.rand(5, 2) 
## 5 rows, 2 cols, uniform distribution
## the numbers change everytime

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

By fixing the random seed, you can make it reproducible

In [45]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

If you want to generate random numbers from normal distribution (standard norml), then 

In [46]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [47]:
np.random.randint(low=0, high=100, size=(5,2)) 

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

## Element-wise operations

In [49]:
a = np.arange(5)
a


array([0, 1, 2, 3, 4])

In [50]:
a + 1

array([1, 2, 3, 4, 5])

In [51]:
a * 2

array([0, 2, 4, 6, 8])

In [52]:
10 + a / 100

array([10.  , 10.01, 10.02, 10.03, 10.04])

In [54]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [55]:
a + b


array([1.  , 2.44, 3.96, 5.56, 7.24])

In [57]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

## Comparison operations

In [60]:
a

array([0, 1, 2, 3, 4])

In [59]:
a >= 2

array([False, False,  True,  True,  True])

In [61]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [62]:
a > b

array([False, False,  True,  True,  True])

In [63]:
a [ a > b ]

array([2, 3, 4])

## Summarizing operations

In [64]:
a

array([0, 1, 2, 3, 4])

In [65]:
a.max()

np.int64(4)

In [67]:
a.min()

np.int64(0)

In [68]:
a.mean()

np.float64(2.0)

In [66]:
a.sum()

np.int64(10)

In [69]:
a.std()

np.float64(1.4142135623730951)

In [70]:
n

array([[ 1, 20,  0],
       [ 4,  5,  0],
       [ 1,  1,  0]])

In [72]:
n.min()

np.int64(0)